# Generated by Django 3.0.8 on 2020-08-29 09:25

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200817_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(upload_to=users.models.PathAndRename('pics/2020/08/29')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_image',
            field=models.ImageField(default='default.png', upload_to=users.models.PathAndRename('profile/2020/08/29')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_resume',
            field=models.FileField(default='resume.pdf', upload_to=users.models.PathAndRename('files/2020/08/29')),
        ),
    ]
