# Generated by Django 3.0.8 on 2020-08-31 17:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200829_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(default='Teensconnect.jpg', upload_to=users.models.PathAndRename('pics/2020/08/31')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_image',
            field=models.ImageField(default='avatar.jpg', upload_to=users.models.PathAndRename('profile/2020/08/31')),
        ),
        migrations.AlterField(
            model_name='userextradetails',
            name='user_resume',
            field=models.FileField(default='resume-samples.pdf', upload_to=users.models.PathAndRename('files/2020/08/31')),
        ),
    ]
